//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motherboard : Component
    {
        public int MotherboardId { get; set; }
        public string Pins { get; set; }
        public string PCISlots { get; set; }
        public string Connectors { get; set; }
        public string Chips { get; set; }
        public string MemorySlots { get; set; }
        public string Type { get; set; }
    }
}
