//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processor : Component
    {
        public int ProcessorId { get; set; }
        public string Speed { get; set; }
        public string Memory { get; set; }
        public string Pins { get; set; }
    }
}
